import math

############ EXERCICE 12 ############


"""

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

"""


def highly_divisible_triangular_number(n):
    """
    Function that returns the value of the first triangle number to have over n divisors.

    :param n: the number of divisors we want to reach.
    :return: first triangular number that have over n divisors.
    """
    sum = 0
    i = 1
    factors = 0
    while factors != n + 1 and factors < n + 1:
        factors = 0
        sum += i
        i += 1
        for j in range(1, int(math.sqrt(sum + 1))):
            if sum % j == 0:
                factors += 1
        if factors * 2 > n + 1:
            return sum
            break
