"""Exercise 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""

from typing import List

import typer

from ._registry import exercise


def fibo_sum(limit: int) -> int:
    """Function that returns the sum of the even-valued terms in the Fibonacci sequence
    that are lower than the limit.

    :param limit: value that can't be exceeded by the Fibonacci sequence's terms.
    :return: sum of the even-valued terms in the Fibonacci sequence.
    """
    fibo: List = [1, 2]
    while True:
        next_fibo: int = sum(fibo[-2:])
        if next_fibo >= limit:
            return sum(i for i in fibo if i % 2 == 0)
        fibo.append(next_fibo)


@exercise(name="exercise-2")
def exercise_2(
    limit: int = typer.Option(2, help="Highest number that can be a multiple of 3 or 5."),
) -> None:
    """Exercise 2: sum of the even-valued terms in the Fibonacci sequence.

    :param limit: value that can't be exceeded by the Fibonacci sequence's terms.
    """
    result: int = fibo_sum(limit)
    print(result)


if __name__ == "__main__":
    typer.run(exercise_2)
